<Gerenciador>
    Menu:
        name:'menu'
    Tarefas:
        name:'tarefas'
<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:200
        spacing:20
        Image:
            source:'todo.png'
            size_hint_y:None
            height:60
            
        Botao:
            text:'Tarefas'
            on_release:app.root.current = 'tarefas'
        Botao:
            text:'Pontuação'
        Botao:
            text:'Sair'
            on_release:root.confirmacao()
#Botão do Menu Iniciar
<Botao@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba:0.1,0.5,0.7,1
        Ellipse:
            pos:self.pos
            size:self.height,self.height
        Ellipse:
            pos:self.x+self.width-self.height,self.y
            size:self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height
    
<Tarefas>:
    BoxLayout:
        # canvas:
        #     Color:
        #         rgba:(1,1,1,.5)
        #     Rectangle:
        #         size:self.size
        #         pos:self.pos            
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:app.root.current="menu"
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        # ScrollView:
        #     BoxLayout:
        #         id:box
        #         orientation: 'vertical'
        #         size_hint_y:None
        #         height:self.minimum_height
        # BoxLayout:
        #     size_hint_y:None
        #     height:60
        # TextInput:
        #     id:texto
        # Button:
        #     text:'+'
        #     size_hint_x:None
        #     width:60
        #     on_release:root.addItem() 
        BoxLayout:
            id:box
            orientation: 'vertical'
            size_hint_y:None
            height:self.minimum_height
            # Label:
            #     text:'Qual o botão com a cor .format()'
            #     font_size:30                
        BoxLayout:
            id:btnBox
            orientation:'vertical'
            padding:100
            spacing:30        
            # Button:
            #     id:btnA            
            #     textColor:'black'
            #     canvas:
            #         Color:
            #             rgba:1, 1, 0, 0.8                        
            #         Rectangle:
            #             size:self.size
            #             pos:self.pos
            #     text:'Amarelo'
            #     on_release:app.root.get_screen('tarefas').upScore()   
            # Button:
            #     text:'Vermelho'
            #     canvas:
            #         Color:
            #             rgba:1, 0, 0, 0.8
            #         Rectangle:
            #             size:self.size
            #             pos:self.pos
            #     on_release:app.root.get_screen('tarefas').upScore()        
            # Button:
            #     text:'Azul'
            #     canvas:
            #         Color:
            #             rgba:0, 1+0, 1, 0.8
            #         Rectangle:
            #             size:self.size
            #             pos:self.pos
            #     on_release:app.root.get_screen('tarefas').upScore()   
            # Button:
            #     text:'Verde'
            #     canvas:
            #         Color:
            #             rgba:0, 1, 0, 0.8                
            #         Rectangle:
            #             size:self.size
            #             pos:self.pos
            #     on_release:app.root.get_screen('tarefas').upScore()   
    BoxLayout:
        id:boxScore
        size_hint_y:None
        height:60
        Label:
            text:'Score'
            size_hint_x:None
            width:120
            font_size:30            
        Label:
            id:score
            text:'1'
            font_size:30              
        Button:
            text:'+'
            size_hint_x:None
            width:60
            on_release:root.addWidget()        
<Tarefa>:
    size_hint_y:None
    height:200
    Label:        
        id:label
        font_size: 30    
#     Button:
#         text:'x'
#         size_hint_x:None
#         width:60
#         on_release:app.root.get_screen('tarefas').removeWidget(root)